pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('jenkins-cicd-demo') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-cicd-demo') {
                    sh 'npm test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('jenkins-cicd-demo') {
                    sh 'docker build -t jenkins-cicd-demo .'
                }
            }
        }

        stage('Docker Run/Deploy') {
            steps {
                sh '''
                    docker stop jenkins-cicd-demo || true
                    docker rm jenkins-cicd-demo || true
                    docker run -d --name jenkins-cicd-demo -p 8081:80 jenkins-cicd-demo
                '''
            }
        }
    }
# post sectionn
    post {
        success {
            echo 'CI/CD Pipeline completed successfully!'
        }

        failure {
            echo 'CI/CD Pipeline failed. Please check the console output.'
        }

        always {
            echo 'Pipeline execution completed.'
        }
    }
}